# Combinación de registros de presencia (DwC) con fichas de especies (PLIC)

**Bibliotecas de Python**

In [1]:
import pandas as pd

**Entradas**

In [2]:
# Archivo con registros de presencia
INPUT_SPECIES_OCCURRENCES = "input/occurrences.csv"

# Archivo con fichas de especies
INPUT_SPECIES_PAGES = "input/plinian_core.txt"

# Archivo con taxonomía de las fichas de especies
INPUT_SPECIES_PAGES_TAXON = "input/taxon.txt"

**Salidas**

In [3]:
# Archivo de salida
OUTPUT_SPECIES_OCCURRENCES_PAGES = "output/species_occurrences_pages.csv"

**Procesamiento**

In [4]:
# Carga de dataframes
input_species_occurrences_df = pd.read_csv(INPUT_SPECIES_OCCURRENCES, sep='\t', encoding='utf_8')
input_species_pages_df = pd.read_csv(INPUT_SPECIES_PAGES, sep='\t', encoding='utf_8')
input_species_pages_taxon_df = pd.read_csv(INPUT_SPECIES_PAGES_TAXON, sep='\t', encoding='utf_8')

/home/mfvargas/anaconda3/envs/presencia-join-fichas/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (10,14,18,39,40,41,43,45,46,48) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
# Filtrado de la taxonomía de las páginas de especies
species_pages_taxon_df = input_species_pages_taxon_df[input_species_pages_taxon_df['class'] == 'Aves']

species_pages_taxon_df

,id,taxonID,acceptedNameUsageID,parentNameUsageID,scientificName,kingdom,phylum,class,order,family,genus,subgenus,specificEpithet,infraspecificEpithet,taxonRank,vernacularName
3,53407.0,53407.0,53407.0,53406.0,Caracara cheriway,Animalia,Chordata,Aves,Falconiformes,Falconidae,Caracara,NaN,cheriway,NaN,species,"Cargahuesos, quebrantahuesos, querque, caracar..."
6,52453.0,52453.0,52453.0,52452.0,Mionectes oleagineus,Animalia,Chordata,Aves,Passeriformes,Tyrannidae,Mionectes,NaN,oleagineus,NaN,species,Mosquerito aceitunado
7,52080.0,52080.0,52080.0,52078.0,Puffinus pacificus,Animalia,Chordata,Aves,Procellariformes,Procellariidae,Puffinus,NaN,pacificus,NaN,species,Pardela colicuña
24,53651.0,53651.0,53651.0,52710.0,Arremon costaricensis,Animalia,Chordata,Aves,Passeriformes,Emberizidae,Arremon,NaN,costaricensis,NaN,species,Saltón cabecinegro
28,52496.0,52496.0,52496.0,76896.0,Pheugopedius maculipectus,Animalia,Chordata,Aves,Passeriformes,Troglodytidae,Pheugopedius,NaN,maculipectus,NaN,species,Soterrey pechimoteado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4983,70370.0,70370.0,70370.0,52870.0,Crotophaga major,Animalia,Chordata,Aves,Cuculiformes,Cuculidae,Crotophaga,NaN,major,NaN,species,Garrapatero grande
4984,52143.0,52143.0,52143.0,51869.0,Calidris fuscicollis,Animalia,Chordata,Aves,Charadriiformes,Scolopacidae,Calidris,NaN,fuscicollis,NaN,species,"Becacina, patudo, correlimos lomiblanco"
4986,52248.0,52248.0,52248.0,52033.0,Heliomaster longirostris,Animalia,Chordata,Aves,Apodiformes,Trochilidae,Heliomaster,NaN,longirostris,NaN,species,"Colibrí, gorrión, colibrí piquilargo"
4997,51801.0,51801.0,51801.0,51800.0,Myiobius atricaudus,Animalia,Chordata,Aves,Passeriformes,Tyrannidae,Myiobius,NaN,atricaudus,NaN,species,Mosquerito colinegro
5006,53746.0,53746.0,53746.0,71081.0,Ibycter americanus,Animalia,Chordata,Aves,Falconiformes,Falconidae,Ibycter,NaN,americanus,NaN,species,"Cacao, come-cacao, deslenguado, caracara avíspera"

In [6]:
# Merge de fichas de especies y taxonomía
species_pages_df = pd.merge(species_pages_taxon_df[['taxonID','class','order','family','genus', 'scientificName']], 
                            input_species_pages_df[['id','HabitatUnstructured']], 
                            left_on='taxonID', 
                            right_on='id',
                            how='inner')

species_pages_df

,taxonID,class,order,family,genus,scientificName,id,HabitatUnstructured
0,53407.0,Aves,Falconiformes,Falconidae,Caracara,Caracara cheriway,53407.0,"Prefieren las áreas abiertas, sabanas, pastiza..."
1,52453.0,Aves,Passeriformes,Tyrannidae,Mionectes,Mionectes oleagineus,52453.0,Viven en los niveles bajos de los bosques húme...
2,52080.0,Aves,Procellariformes,Procellariidae,Puffinus,Puffinus pacificus,52080.0,"Son pelágicas, y se ubican bien lejos de la co..."
3,53651.0,Aves,Passeriformes,Emberizidae,Arremon,Arremon costaricensis,53651.0,Viven en bosques y matorrales secundarios húme...
4,52496.0,Aves,Passeriformes,Troglodytidae,Pheugopedius,Pheugopedius maculipectus,52496.0,"Viven en los matorrales a lo largo de ríos, ár..."
...,...,...,...,...,...,...,...,...
865,70370.0,Aves,Cuculiformes,Cuculidae,Crotophaga,Crotophaga major,70370.0,NaN
866,52143.0,Aves,Charadriiformes,Scolopacidae,Calidris,Calidris fuscicollis,52143.0,Frecuenta los bordes arenosos y lodosos de lag...
867,52248.0,Aves,Apodiformes,Trochilidae,Heliomaster,Heliomaster longirostris,52248.0,"Frecuenta el dosel y los bordes del bosque, ár..."
868,51801.0,Aves,Passeriformes,Tyrannidae,Myiobius,Myiobius atricaudus,51801.0,Viven en bosques secundarios jóvenes o charral...
869,53746.0,Aves,Falconiformes,Falconidae,Ibycter,Ibycter americanus,53746.0,Viven en el dosel y el borde de los bosques hú...

In [8]:
species_occurrences_df = input_species_occurrences_df

# Filtrado de registros de presencia (opcional)
species_occurrences_df = input_species_occurrences_df[input_species_occurrences_df['class'] == 'Aves']
# species_occurrences_df = species_occurrences_df[species_occurrences_df['basisOfRecord'] == 'PRESERVED_SPECIMEN']

species_occurrences_df

,gbifID,datasetKey,occurrenceID,kingdom,phylum,class,order,family,genus,species,...,identifiedBy,dateIdentified,license,rightsHolder,recordedBy,typeStatus,establishmentMeans,lastInterpreted,mediaType,issue
86,1147096324,7f6dd0f7-9ed4-49c0-bb71-b2a9c7fed9f1,4cb612de-6409-4592-96da-e6b5f99c58ec,Animalia,Chordata,Aves,Passeriformes,Furnariidae,Xiphorhynchus,Xiphorhynchus erythropygius,...,NaN,NaN,CC0_1_0,NaN,Lewis F Kibler,NaN,NATIVE,2019-11-13T20:01:17.769Z,NaN,COORDINATE_ROUNDED
87,1147031614,7f6dd0f7-9ed4-49c0-bb71-b2a9c7fed9f1,01a79de2-42a9-478b-bcef-7228998ddf56,Animalia,Chordata,Aves,Passeriformes,Thamnophilidae,Dysithamnus,Dysithamnus mentalis,...,NaN,NaN,CC0_1_0,NaN,Kathi Borgmann,NaN,NATIVE,2019-11-13T20:01:16.612Z,NaN,COORDINATE_ROUNDED
96,1319768729,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/371868590-dcfa-4cc4-...,Animalia,Chordata,Aves,Falconiformes,Falconidae,Micrastur,Micrastur ruficollis,...,NaN,NaN,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:22.686Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84
100,1321781972,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/3ca8d95e0-5517-4497-...,Animalia,Chordata,Aves,Apodiformes,Trochilidae,Selasphorus,Selasphorus flammula,...,NaN,NaN,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:36.540Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84
108,1321103264,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/3ac840d95-f6e3-46ca-...,Animalia,Chordata,Aves,Apodiformes,Trochilidae,Eupherusa,Eupherusa eximia,...,NaN,NaN,CC0_1_0,NaN,C. Van Patten,NaN,NaN,2020-01-15T13:05:34.728Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544967,1320759328,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/39d548586-5d1f-4224-...,Animalia,Chordata,Aves,Passeriformes,Troglodytidae,Campylorhynchus,Campylorhynchus zonatus,...,NaN,NaN,CC0_1_0,NaN,C. Underwood,NaN,NaN,2020-01-15T13:05:07.770Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84
544968,1319389964,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/360c54302-b763-40c3-...,Animalia,Chordata,Aves,Passeriformes,Tyrannidae,Empidonax,Empidonax flavescens,...,NaN,NaN,CC0_1_0,NaN,R. Ridgway,NaN,NaN,2020-01-15T13:05:25.121Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84
544969,1322229341,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/3de608709-4938-4311-...,Animalia,Chordata,Aves,Passeriformes,Vireonidae,Hylophilus,Hylophilus decurtatus,...,NaN,NaN,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:09.761Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84
544972,1318093413,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/32762ad56-0081-4c44-...,Animalia,Chordata,Aves,Passeriformes,Tyrannidae,Serpophaga,Serpophaga cinerea,...,NaN,NaN,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:03.154Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84
544984,1321755540,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/3c96068ac-9555-4d0d-...,Animalia,Chordata,Aves,Passeriformes,Thraupidae,Tangara,Tangara larvata,...,NaN,NaN,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:10.712Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84

In [9]:
# Dataframe de salida
species_occurrences_pages_df = pd.merge(species_occurrences_df,
                                        species_pages_df[['scientificName','HabitatUnstructured']], 
                                        left_on='species', 
                                        right_on='scientificName',
                                        how='left')

species_occurrences_pages_df

,gbifID,datasetKey,occurrenceID,kingdom,phylum,class,order,family,genus,species,...,license,rightsHolder,recordedBy,typeStatus,establishmentMeans,lastInterpreted,mediaType,issue,scientificName_y,HabitatUnstructured
0,1147096324,7f6dd0f7-9ed4-49c0-bb71-b2a9c7fed9f1,4cb612de-6409-4592-96da-e6b5f99c58ec,Animalia,Chordata,Aves,Passeriformes,Furnariidae,Xiphorhynchus,Xiphorhynchus erythropygius,...,CC0_1_0,NaN,Lewis F Kibler,NaN,NATIVE,2019-11-13T20:01:17.769Z,NaN,COORDINATE_ROUNDED,Xiphorhynchus erythropygius,Viven en el dosel y en los bordes de los bosqu...
1,1147031614,7f6dd0f7-9ed4-49c0-bb71-b2a9c7fed9f1,01a79de2-42a9-478b-bcef-7228998ddf56,Animalia,Chordata,Aves,Passeriformes,Thamnophilidae,Dysithamnus,Dysithamnus mentalis,...,CC0_1_0,NaN,Kathi Borgmann,NaN,NATIVE,2019-11-13T20:01:16.612Z,NaN,COORDINATE_ROUNDED,Dysithamnus mentalis,Frecuenta el sotobosque de los bosques maduros...
2,1319768729,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/371868590-dcfa-4cc4-...,Animalia,Chordata,Aves,Falconiformes,Falconidae,Micrastur,Micrastur ruficollis,...,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:22.686Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84,Micrastur ruficollis,"Viven en el sotobosque del bosque húmedo, bosq..."
3,1321781972,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/3ca8d95e0-5517-4497-...,Animalia,Chordata,Aves,Apodiformes,Trochilidae,Selasphorus,Selasphorus flammula,...,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:36.540Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84,Selasphorus flammula,"Prefieren áreas abiertas con arbustos, páramos..."
4,1321103264,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/3ac840d95-f6e3-46ca-...,Animalia,Chordata,Aves,Apodiformes,Trochilidae,Eupherusa,Eupherusa eximia,...,CC0_1_0,NaN,C. Van Patten,NaN,NaN,2020-01-15T13:05:34.728Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84,Eupherusa eximia,"Viven en el interior, dosel y en los bordes de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477170,1320759328,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/39d548586-5d1f-4224-...,Animalia,Chordata,Aves,Passeriformes,Troglodytidae,Campylorhynchus,Campylorhynchus zonatus,...,CC0_1_0,NaN,C. Underwood,NaN,NaN,2020-01-15T13:05:07.770Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84,Campylorhynchus zonatus,Viven en las aberturas y bordes de los bosques...
477171,1319389964,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/360c54302-b763-40c3-...,Animalia,Chordata,Aves,Passeriformes,Tyrannidae,Empidonax,Empidonax flavescens,...,CC0_1_0,NaN,R. Ridgway,NaN,NaN,2020-01-15T13:05:25.121Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84,Empidonax flavescens,Viven en el dosel y en los bordes de los bosqu...
477172,1322229341,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/3de608709-4938-4311-...,Animalia,Chordata,Aves,Passeriformes,Vireonidae,Hylophilus,Hylophilus decurtatus,...,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:09.761Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84,Hylophilus decurtatus,"Viven en el dosel y en el borde del bosque, la..."
477173,1318093413,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/32762ad56-0081-4c44-...,Animalia,Chordata,Aves,Passeriformes,Tyrannidae,Serpophaga,Serpophaga cinerea,...,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:03.154Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84,Serpophaga cinerea,Está restringido a las quebradas y ríos rápido...
477174,1321755540,821cc27a-e3bb-4bc5-ac34-89ada245069d,http://n2t.net/ark:/65665/3c96068ac-9555-4d0d-...,Animalia,Chordata,Aves,Passeriformes,Thraupidae,Tangara,Tangara larvata,...,CC0_1_0,NaN,J. Zeledon,NaN,NaN,2020-01-15T13:05:10.712Z,NaN,GEODETIC_DATUM_ASSUMED_WGS84,Tangara larvata,Frecuenta los niveles superiores de los bosque...

In [10]:
# Exportación a CSV
species_occurrences_pages_df.to_csv(OUTPUT_SPECIES_OCCURRENCES_PAGES, index = False)